name: Test GH Action

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]


jobs:
  test-gh-executable-files:
    name: Testing Executable Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculating Next Release Version Using executable files
        env:
          GithubToken: ${{ github.token }}
          ReleaseSettingsPath: ./cicd/releaseSettings.json
          PullRequestNumber: ${{ github.event.number }}
        run: ./app/cangulo.nuke.releasecreator CalculateNextReleaseNumber --root .

  test-gh-action-directly:
    name: Testing Release Candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculating Next Release Version Using Release Candidate
        uses: cangulo-actions/cangulo.nuke.releasecreator@release/v0.0.1
        with:
          releaseSettingsPath: ./cicd/releaseSettings.json
          token: ${{ github.token }}
          onlyCalculateReleaseNumber: true